import { useEffect, useRef, useState } from 'react';
import type { ChangeEvent, FormEvent } from 'react';
import { BookOpen, ExternalLink, FileText, ImagePlus, Loader2, Save, Upload } from 'lucide-react';
import { profileApi } from '../lib/profileApi';
import { useAuth } from '../auth/AuthProvider';
import { errorClass, fieldClass, primaryButton, secondaryButton } from '../components/esc/learningTypes';

type Details = { user: { name: string; email: string }; profile: any; activity: { assignmentsCompleted: number; notesUploaded: number; resourcesAdded: number } };
const cacheKey = (id: string) => `esc-profile-v1:${id}`;

async function compressImage(file: File): Promise<File> {
  if (!file.type.startsWith('image/') || file.size < 700_000) return file;
  const image = await createImageBitmap(file); const scale = Math.min(1, 1280 / Math.max(image.width, image.height));
  const canvas = document.createElement('canvas'); canvas.width = Math.round(image.width * scale); canvas.height = Math.round(image.height * scale);
  canvas.getContext('2d')?.drawImage(image, 0, 0, canvas.width, canvas.height);
  const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, 'image/jpeg', .82));
  return blob ? new File([blob], `${file.name.replace(/\.[^.]+$/, '')}.jpg`, { type: 'image/jpeg' }) : file;
}

export default function ProfilePage() {
  const { user } = useAuth();
  const [details, setDetails] = useState<Details | null>(null); const [notes, setNotes] = useState<any[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState({ class: '', school_name: '', exam_preparing: '', subjects: '', study_progress: 0 });
  const [note, setNote] = useState({ title: '', subject: '', resourceLink: '', file: undefined as File | undefined });
  const [addingNote, setAddingNote] = useState(false); const [imageUrl, setImageUrl] = useState(''); const imageUrlRef = useRef('');
  const setPreview = (url: string) => { if (imageUrlRef.current) URL.revokeObjectURL(imageUrlRef.current); imageUrlRef.current = url; setImageUrl(url); };
  const hydrate = (value: Details) => { setDetails(value); const p = value.profile || {}; setForm({ class: p.class || p.grade || '', school_name: p.schoolName || '', exam_preparing: p.examPreparing || p.goal || '', subjects: (p.subjects || []).join(', '), study_progress: p.studyProgress || 0 }); };
  useEffect(() => {
    let active = true; const cached = user && sessionStorage.getItem(cacheKey(user.id));
    if (cached) { try { hydrate(JSON.parse(cached)); setLoading(false); } catch { sessionStorage.removeItem(cacheKey(user!.id)); } }
    void Promise.all([profileApi.details(), profileApi.notes()]).then(([profile, noteData]) => { if (!active) return; hydrate(profile); setNotes(noteData.notes); if (user) sessionStorage.setItem(cacheKey(user.id), JSON.stringify(profile)); setLoading(false); }).catch(reason => { if (active) { setError(reason instanceof Error ? reason.message : 'Unable to load your profile.'); setLoading(false); } });
    return () => { active = false; if (imageUrlRef.current) URL.revokeObjectURL(imageUrlRef.current); };
  }, [user]);
  useEffect(() => { if (!details?.profile?.profileImageUrl) return; void profileApi.file(details.profile.profileImageUrl).then(blob => setPreview(URL.createObjectURL(blob))).catch(() => undefined); }, [details?.profile?.profileImageUrl]);
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { const response = await profileApi.update({ ...form, subjects: form.subjects.split(',').map(x => x.trim()).filter(Boolean) }); const next = { ...details!, profile: response.profile, activity: response.activity }; hydrate(next); if (user) sessionStorage.setItem(cacheKey(user.id), JSON.stringify(next)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to save changes.'); } finally { setSaving(false); } };
  const uploadImage = async (event: ChangeEvent<HTMLInputElement>) => { const selected = event.target.files?.[0]; if (!selected) return; try { const file = await compressImage(selected); const response = await profileApi.uploadImage(file); hydrate({ ...details!, profile: response.profile }); setPreview(URL.createObjectURL(file)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to upload image.'); } };
  const addNote = async (event: FormEvent) => { event.preventDefault(); setAddingNote(true); setError(''); try { const response = await profileApi.addNote(note); setNotes(current => [response.note, ...current]); setNote({ title: '', subject: '', resourceLink: '', file: undefined }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to add this resource.'); } finally { setAddingNote(false); } };
  if (loading) return <div className="flex flex-1 items-center justify-center"><div className="w-full max-w-5xl animate-pulse space-y-5 p-6"><div className="h-40 rounded-3xl bg-white/[.06]" /><div className="grid gap-4 sm:grid-cols-3">{[1, 2, 3].map(i => <div key={i} className="h-24 rounded-2xl bg-white/[.04]" />)}</div></div></div>;
  const p = details?.profile || {}; const displayName = details?.user?.name || user?.name || 'Learner';
  return <div className="min-w-0 flex-1 overflow-y-auto px-4 py-7 sm:px-8 lg:px-10"><div className="mx-auto max-w-5xl"><header className="rounded-3xl border border-white/[.09] bg-gradient-to-br from-[#282033] to-[#17181e] p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><label className="group relative grid h-20 w-20 shrink-0 cursor-pointer place-items-center overflow-hidden rounded-2xl border border-[#c3afff]/25 bg-[#b7a1f8]/10 text-2xl font-semibold text-[#d6c5ff]">{imageUrl ? <img src={imageUrl} className="h-full w-full object-cover" alt="Profile" /> : displayName[0].toUpperCase()}<span className="absolute inset-0 grid place-items-center bg-black/55 opacity-0 transition group-hover:opacity-100"><ImagePlus size={19} /></span><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadImage} /></label><div><p className="esc-eyebrow">STUDENT PROFILE</p><h1 className="mt-2 text-2xl font-medium tracking-tight sm:text-3xl">{displayName}</h1><p className="mt-1 text-sm text-[#aaa3b5]">{p.class || p.grade || 'Add your class'} · {p.schoolName || 'Add your school'}</p></div></div></header>
    {error && <p className={`${errorClass} mt-5`}>{error}</p>}
    <section className="mt-5 grid gap-4 sm:grid-cols-3">{[{ label: 'Assignments completed', value: details?.activity.assignmentsCompleted || 0 }, { label: 'Notes uploaded', value: details?.activity.notesUploaded || 0 }, { label: 'Resources added', value: details?.activity.resourcesAdded || 0 }].map(stat => <div key={stat.label} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><p className="text-2xl font-medium">{stat.value}</p><p className="mt-1 text-xs text-[#98929f]">{stat.label}</p></div>)}</section>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><form onSubmit={save} className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><div className="flex items-center gap-2 text-sm font-medium"><BookOpen size={16} className="text-[#c5b0f4]" /> Academic information</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs text-[#aaa3b5]">Class<input className={fieldClass} value={form.class} onChange={e => setForm({ ...form, class: e.target.value })} placeholder="e.g. Grade 12" /></label><label className="text-xs text-[#aaa3b5]">School<input className={fieldClass} value={form.school_name} onChange={e => setForm({ ...form, school_name: e.target.value })} placeholder="Your school" /></label><label className="text-xs text-[#aaa3b5]">Exam preparing for<input className={fieldClass} value={form.exam_preparing} onChange={e => setForm({ ...form, exam_preparing: e.target.value })} placeholder="e.g. JEE Main" /></label><label className="text-xs text-[#aaa3b5]">Study progress ({form.study_progress}%)<input className="mt-4 w-full accent-[#c3afff]" type="range" min="0" max="100" value={form.study_progress} onChange={e => setForm({ ...form, study_progress: Number(e.target.value) })} /></label><label className="text-xs text-[#aaa3b5] sm:col-span-2">Subjects <span className="text-[#77717e]">(comma separated)</span><input className={fieldClass} value={form.subjects} onChange={e => setForm({ ...form, subjects: e.target.value })} placeholder="Physics, Chemistry, Mathematics" /></label></div><button disabled={saving} className={`${primaryButton} mt-5`}>{saving ? <Loader2 className="animate-spin" size={15} /> : <Save size={15} />} Save changes</button></form>
    <section className="rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><div className="flex items-center gap-2 text-sm font-medium"><Upload size={16} className="text-[#c5b0f4]" /> Add note or resource</div><form onSubmit={addNote} className="mt-5 space-y-3"><input required className={fieldClass} value={note.title} onChange={e => setNote({ ...note, title: e.target.value })} placeholder="Resource title" /><input className={fieldClass} value={note.subject} onChange={e => setNote({ ...note, subject: e.target.value })} placeholder="Subject (optional)" /><input className={fieldClass} value={note.resourceLink} onChange={e => setNote({ ...note, resourceLink: e.target.value })} type="url" placeholder="External link (optional)" /><label className={`${fieldClass} flex cursor-pointer items-center gap-2`}><FileText size={15} /> {note.file?.name || 'Upload PDF or image (max 5 MB)'}<input className="sr-only" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e => setNote({ ...note, file: e.target.files?.[0] })} /></label><button disabled={addingNote} className={`${secondaryButton} w-full`}>{addingNote ? <Loader2 className="animate-spin" size={15} /> : <Upload size={15} />} Add to library</button></form></section></div>
    <section className="mt-5 rounded-2xl border border-white/[.08] bg-white/[.025] p-5"><h2 className="text-sm font-medium">Notes & resources</h2><div className="mt-4 space-y-2">{notes.length ? notes.map(item => <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-white/[.03] px-4 py-3"><div><p className="text-sm">{item.title}</p><p className="mt-1 text-xs text-[#938c99]">{item.subject || 'General'} · {new Date(item.createdAt).toLocaleDateString()}</p></div>{item.resourceLink ? <a className="inline-flex items-center gap-1 text-xs text-[#cdbaff]" href={item.resourceLink} target="_blank" rel="noreferrer">Open link <ExternalLink size={13} /></a> : item.fileUrl ? <button className="inline-flex items-center gap-1 text-xs text-[#cdbaff]" onClick={() => void profileApi.file(item.fileUrl).then(blob => window.open(URL.createObjectURL(blob), '_blank', 'noopener'))}>Open file <FileText size={13} /></button> : null}</article>) : <p className="py-5 text-sm text-[#938c99]">Your uploaded notes and saved links will appear here.</p>}</div></section>
  </div></div>;
}
